---

- name: YUM_REPOSITORY | Configure yum sources
  become: true
  become_user: root
  vars:
    ansible_python_interpreter: /usr/bin/python
  yum_repository:
    name: "google-chrome"
    description: "google-chrome"
    baseurl: "http://dl.google.com/linux/chrome/rpm/stable/x86_64"
    file: "/etc/yum.repos.d/google-chrome.repo"
    gpgkey: "https://dl.google.com/linux/linux_signing_key.pub"
    gpgcheck: true
    enabled: true
    enablegroups: true
  register: task_result

- name: flush yum cache
  become: true
  become_user: root
  command: yum clean all
  args:
    warn: false
  when: task_result.changed

- name: YUM | Update all packages
  become: true
  become_user: root
  vars:
    ansible_python_interpreter: /usr/bin/python
  yum:
    name:
      - google-chrome-stable
      - chrome-remote-desktop
    state: latest
    update_cache: true
